### ISSUE TITLE
How to patch the transport file to the sender?

### ISSUE THREAD

**Issue by JahedulAnowar** [AMWA-TV/nmos-device-connection-management#113]
I tried to register a single node to the registry and was able to get the transport file using the connection API. Now i am not sure of how to patch this transport file to the receiver (assuming the same node can receive as i only have one node) node. Is it possible to do so? Does it require the same id as the sender id? or do i need a different node to receive the file?

This might be a very silly question. As i am totally new into this, it would be very helpful if i could get some hint or the links to documentation leading to the solution. 
Thank you.

**Comment by garethsb** [comment]
Let's assume your NMOS Node has a Sender and a Receiver, with compatible transports and formats.
So, your Sender would be at:
**http://api.example.com/x-nmos/connection/v1.1/single/senders/{senderId}**
And your Receiver at:
**http://api.example.com/x-nmos/connection/v1.1/single/receivers/{receiverId}**
(where {senderId} and {receiverId} stand for the relevant UUIDs)

You did an HTTP GET for:
**http://api.example.com/x-nmos/connection/v1.1/single/senders/{senderId}/transportfile**
And got an SDP file back. So far so good!

In order to have the Receiver activate a connection to that Sender immediately, you need to make an HTTP PATCH request to:
**http://api.example.com/x-nmos/connection/v1.1/single/receivers/{receiverId}/staged**

The body of the PATCH request is a JSON object, with a few properties:
* The `sender_id`
* The `activation` object, indicating the connection should be made immediately
* The `transport_file` object, containing the SDP file encoded as a JSON string

So something like:
```json
{
  "sender_id": "{senderId}",
  "activation": {
    "mode": "activate_immediate"
  },
  "transport_file": {
    "type": "application/sdp",
    "data": "v=0\r\n....."
  }
}
```

If you want to play with software to see how this works, the open-source [AMWA NMOS Testing Tool](https://github.com/AMWA-TV/nmos-testing), the free-to-download [Riedel NMOS Explorer](https://www.riedel.net/downloads/firmware-software/) desktop app, or the open-source [Sony nmos-js Client](https://github.com/sony/nmos-js) webapp, could be good places to start.

**Comment by JahedulAnowar** [comment]
Thank you for your prompt reply. 

I tried with curl: `curl -X PATCH -H "Content-Type: application/json" -d '{"sender_id": "99123ce4-23a9-5c1a-b45e-0abcd3dc617a", "activation": {"mode": "activate_immediate"}, "transport_file": {"type": "application/sdp", "data": "v=0"}}' http://111.111.111.11:3215/x-nmos/connection/v1.1/single/receivers/a09919d1-f8b7-1234-bb08-z636eef4zz47/staged`

I get this error: `{"code":500,"error":"Internal Error","debug":"Transport file error - sdp parse error - expected a line for origin at line 2"}`
I am not sure if my command is right or not.

Also is there any way to directly send the contents of SDP as a `.txt` or `.json` file?

**Comment by garethsb** [comment]
You need to put the whole SDP file into the **transport_file.data**, remembering that e.g. new lines are escaped as `\r\n` in JSON strings. This is the only way to pass an SDP file to an IS-05 Receiver.

**Comment by JahedulAnowar** [comment]
Ok, i get it now, it requires the full info from SDP file.
I was also successful in communicating with physical transmitters and receivers.

Thank you very much for your help.
