### ISSUE TITLE
Ambiguity on how to represent non-existent transportfile in receiver PATCH

### ISSUE THREAD

**Issue by jonvmey** [AMWA-TV/nmos-device-connection-management#117]
Some ambiguity appears to exist regarding how to indicate that no transportfile exists in a PATCH to an RTP receiver (eg. "disconnecting" the receiver). Some implementations have chosen to send

    "transport_file": {
        "type": "application/sdp",
        "data": ""
    }

in this case based on wording from TR-1001-1:2018.

Based on discussions from Slack the intended way to indicate no transportfile is

    "transport_file": {
        "type": null,
        "data": null
    }

and if `"type"` is set to `"application/sdp"` then `"data"` should be expected to contain a valid SDP file which an empty string is not.

Would it be worthwhile to update the description of the receiver transportfile schema to something like

> "description": "Transport file parameters. 'data' and 'type' must both be strings or both be null. **If 'type' is non-null 'data' is expected to contain a valid instance of the specified media type**"

to negate this ambiguity?

**Comment by garethsb** [comment]
I think the suggested clarification is a good idea.
We also ought to fix the handful of example files which currently have `"type": "application/sdp", "data": ""`.

The IS-05 spec already makes it clear, I hope, that the only thing necessary to disconnect a Receiver is to set `"master_enable": false`. This is reiterated by the adjusted wording in JT-NM TR-1001-1 from the start of **11.4    Receiver Disconnect Convention**:

 At times, the Broadcast Controller might seek to disconnect a receiver – such that the receiver receives no signal and takes a receiver-dependent action. Some early receiver implementations used multicast addresses of 0.0.0.0 and/or blank/empty/null SDP files to indicate disconnect status.
 In order to avoid doubt and to maximize interoperability, the IS-05 master_enable property shall be the definitive indicator of the status of a receiver.  
 When a broadcast controller activates with master_enable set to false, the receiver shall enter the disconnect state. When a broadcast controller activates with master_enable set to true, the receiver shall attempt to enter the connected state. 
 Consistent with REST principles, Receivers should persist the values of the transport-file and transport-parameters if they are not altered in the activation, even if the activation indicates a disconnection.
