### ISSUE TITLE
Nullable fields in `transport_params`

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-device-connection-management#140]
[The JSON Schema for RTP Transport Params](https://specs.amwa.tv/is-05/releases/v1.1.1/APIs/schemas/with-refs/sender_transport_params_rtp.html) doesn't define its properties as nullable explicitly, but they are `null` in the examples given in [Behaviour: RTP Transport Type](https://specs.amwa.tv/is-05/releases/v1.1.1/docs/4.1._Behaviour_-_RTP_Transport_Type.html).

Is this a schema violation or I'm missing something?

**Comment by garethsb** [comment]
That's the Sender schema. The examples are for a Receiver. The Receiver parameters are nullable. https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/APIs/schemas/receiver_transport_params_rtp.json

**Comment by N-Nagorny** [comment]
Indeed, thank you. What about `fec2D_destination_port` particularly?

**Comment by garethsb** [comment]
Agreed, the example does not comply to the schema. Seems to me that when `fec_mode` is `1D`, the value of `fec2D_destination_port` isn't applicable. For other parameters, `null` would be used in this case. For this parameter, and also `rtcp_destination_port` when `rtcp_enabled` is `false`, I think the best thing to do is to set the value to `"auto"`. _Ah, no, I think I'm wrong..._ For starters, you can't have `"auto"` in **/active**, only **/staged**. Hmm. Allowing `null` for those parameters makes sense to me, but since the schema doesn't currently do that, maybe they just have to be a port number but unused. 🤷‍♂️

**Comment by garethsb** [comment]
@andrewbonney points out that several other transport parameters should have real values in **/active** even in circumstances where they aren't applicable - e.g. all of the other `fec_` parameters are redundant if `fec_enabled` is `false` of course!

Since the examples in the Behaviour document are for what should be done in **/staged**, I think the fix is to put `"auto"` in the example you identified, @N-Nagorny. When this is transitioned to **/active**, a Receiver should translate this to a real port number even though it isn't going to be used.

I'll make a PR with that little change.
