### ISSUE TITLE
About master_enable and sender_id

### ISSUE THREAD

**Issue by ghost** [AMWA-TV/nmos-device-connection-management#142]
Hello.

According to what I read [here](https://specs.amwa.tv/is-04/releases/v1.3.1/docs/4.3._Behaviour_-_Nodes.html), a PATCHing of the following JSON:

```
{
  "master_enable": false,
  "transport_params": [
    {
      "multicast_ip": "233.252.2.1"
    }
  ],
  "sender_id": "02bcb69b-751e-4138-9ac9-829f14362e02"
}
```

MUST be rejected, because "master_enable" (subscription active) cannot be false when "sender_id" is not null, am I correct? 

Thanks.

**Comment by garethsb** [comment]
I think that's incorrect.

In the Connection API, `master_enable` and `sender_id` can be set freely.

In the Node API, the `subscription.active` attribute was introduced in a later API version than `subscription.sender_id`, so there is a requirement for backward compatibility that `subscription.sender_id` is `null` whenever `subscription.active` is `false`. There is no means for a client to set these Node API attributes directly.

When a Media Node implements both Connection API and Node API, it must keep these in sync.
* The value of the Connection API **/active** endpoint `master_enable` attribute must be the same as the Node API `subscription.active` attribute.
* Due to the Node API backward compatibility rules, if **/active** `master_enable` is `false`, Node API `subscription.sender_id` must be `null`. Otherwise it must be the same as **/active** `sender_id`.

It's possible that the guidelines at https://specs.amwa.tv/is-05/releases/v1.1.1/docs/3.1._Interoperability_-_IS-04.html could be clearer...

**Comment by ghost** [comment]
Very clear, thanks.

**Comment by peterbrightwell** [comment]
Looks like this can be closed

**Comment by peterbrightwell** [comment]
Architecture Review Group review: closing
