### ISSUE TITLE
Typo in examples/sender-stage-absolute-success.json?

### ISSUE THREAD

**Issue by gervaisj** [AMWA-TV/nmos-device-connection-management#169]
I believe there is a typo in the example for absolute sender activation: `activate_scheduled_relative` should be `activate_scheduled_absolute` (https://github.com/AMWA-TV/is-05/blob/v1.1.x/examples/sender-stage-absolute-success.json#L5)

A similar issue was fixed for receivers in #32, but not for senders.

Doing a quick code search, this seems to be the last occurrence of the typo.

**Comment by garethsb** [comment]
Good spot, thank you. Needs to be fixed in the v1.0.x branch also. This kind of thing wouldn't be caught by schema validation. Perhaps we could run the examples through some additional tests to check e.g. transport_params are valid for the intended sender or receiver and transport_file is in sync.

Adding to @AMWA-TV/nmos-architecture-review backlog.

**Comment by peterbrightwell** [comment]
Fixed in: 

v1.0.x: 639adad666610d6ffe2ec8097051d047cf9469e9
v1.1.x: 055434822c099db8337f73a069fc09141cd640b4
v1.2-dev: 2b74cbe5619e92a14535dfa8499408c841c776d4
