### ISSUE TITLE
v1.0-bulk-stage-confirm.json does not permit a response code of 423 "Locked"

### ISSUE THREAD

**Issue by btrost-harmonicinc** [AMWA-TV/nmos-device-connection-management#31]
When a bulk request is attempted on a resource that is locked, shouldn't the code field in the matching element of the HTTP response contain 423 for its code field? The schema does not currently permit such a response.

I'm presuming that a bulk POST on a locked resource needs to follow the same locking protocol that a PATCH request requires.

**Comment by simonrankine** [comment]
Hi there,

Yes this looks like it needs fixing in the spec. The 423 response should be included in the list of return codes. I'll look into this further and get back to you.

**Comment by garethsb** [comment]
@simonlo-sony pointed this out to me a couple of weeks ago, but I forgot to raise it, oops!

However, I'd like to suggest a different fix. Rather than (or at least in addition to) explicitly listing the likely responses, the schema should allow any 4xx or 5xx code, as the error.json schema does.

This would align correctly with  the documentation of [Error Codes & Responses](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/docs/2.0.%20APIs.md#error-codes--responses), which makes clear that the status codes in the RAML are the specific examples with clearly defined meanings, not an exhaustive list.

What do you people think?

**Comment by btrost-harmonicinc** [comment]
I prefer Gareth's suggested fix.

**Comment by simonrankine** [comment]
Pull request #31 now has a proposed fix for this.
