### ISSUE TITLE
Meaning of "default" in the RTP parameters schemas

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#38]
Similar to #37, I think the intended semantics of the several instances of ``"default"``, and especially, ``"default": "auto"`` in the JSON Schemas should be clarified, or those defaults removed.

Presumably a PATCH /staged request that doesn't include a particular property, means "don't change the value of that property", not "consider I specified the schema default".

I suspect the schema defaults are intended to convey that a newly powered-on device MAY, SHOULD or MUST (I don't know which!) _logically_ start with those defaults.

Of course, the implementer still needs to take care about preparing a response to GET /active, when the schema default is "auto", since the GET requests on /active are specified as follows:

> On activation all instances of "auto" should be resolved into the actual values that will be used

Perhaps the word _should_ in that sentence ought to be MUST? Or is returning "auto" in responses to the /active endpoint actually allowed?

**Comment by garethsb** [comment]
Another instance of default that's potentially confusing:
https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0-activation-schema.json#L33

**Comment by simonrankine** [comment]
Hi Gareth,

Yes, I think what we've hit here is a bit of a hang over from when the spec used to be a bit more explicit about what to do when you turn the device on - this turned out to be a bit too prescriptive hence the now slightly notorious "assume sensible defaults" clause...

I'm happy enough to remove the defaults - as you correctly point out they don't really mean a lot any more so probably just confuse matters. I think that "should" is there to allow for the fact that the device may fail to do that conversion for some reason, and therefore not update the active parameters at all. Either way "auto" should never end up in the /active end point (not least because it makes no sense there).

S

**Comment by simonrankine** [comment]
A couple of commits there that hopefully help, could you take a look and see if you are happy with those please?

**Comment by simonrankine** [comment]
Seconds thoughts, I'll close this and we'll carry on in the pull request #42
