### ISSUE TITLE
Patching a receiver's "transport_file"

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#47]
The v1.0-receiver-stage-schema.json for "transport_file" doesn't make the "data" and "type" required. Is that an oversight? It seems to me it's unfortunate to allow staging just one or other of these fields (and staging an empty object is pointless)?

Looking at it now, the "transport_file" schema ought to be extracted out of the stage/response schemas in the same way as the activation schema.

**Comment by garethsb** [comment]
Also, what should patching"type" to null do, when "data" is omitted or non-null?

We could disallow that with a more complicated schema for "transport_file"?

**Comment by simonrankine** [comment]
Hi Gareth,

It's not an oversight, as otherwise you couldn't do a patch to just change the transport parameters when operating with a device that doesn't use SDP, or to alter master_enable say.

Why would you want to set the transport file without also setting it's type? I mean, IS-05 doesn't strictly prohibit it but I don't imagine you can expect the receiver to do anything useful if you do.

**Comment by garethsb** [comment]
> It's not an oversight, as otherwise you couldn't do a patch to just change the transport parameters when operating with a device that doesn't use SDP, or to alter master_enable say.

Yes, you could; the transport_file field at the top-level is optional.  I'm saying that the two fields *inside* the transport_file field should be required.

> Why would you want to set the transport file without also setting it's type? I mean, IS-05 doesn't strictly prohibit it but I don't imagine you can expect the receiver to do anything useful if you do.

Quite.

**Comment by andrewbonney** [comment]
Resolved by #74
